깃 테스트
CodeSoom/git-training pull request #42
Opened 2021-01-17 10:20 UTC by 2Zero1

테스트 pr

2021-01-17 13:44 UTC, hannut91 approved these changes
굳굳 입니다 ㅎㅎ

2021-01-17 14:41 UTC, 2Zero1 commented
> 굳굳 입니다 ㅎㅎ

이렇게 직접 pr을 달아주시다니
잘부탁드립니다 그랜절 박습네다.

2021-01-19 12:04 UTC, moonkii requested changes
열심히 하시는군요

2021-01-19 12:04 UTC, moonkii commented on test
> +
test

2021-01-19 15:18 UTC, 2Zero1 commented on test
> +
무엇을 test로 바꾸면 되는거죠 조교님

2021-01-20 02:23 UTC, moonkii commented on test
> +
저도 테스트로 남겨본겁니다 ㅋㅋㅋㅋㅋㅋ

2021-05-02 16:07 UTC, closed without merging